name: lakes
channels:
  - conda-forge
  - defaults
dependencies:
  - black=22.6.0
  - chardet
  - ipykernel=6.15.1
  - libxml2
  - numpy=1.22.3
  - pandas=1.4.3
  - matplotlib
  - matplotlib-inline
  - pip=22.2.2
  - polars=0.14.6
  - pylint=2.14.3
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - python=3.8
  - ruff
  - seaborn
  - scipy
  - scikit-learn
  - tqdm=4.64.0
  - pip:
    - -r requirements.txt